name: Convert M3U8 to MPD

on: schedule: - cron: "*/10 * * * *"  # Run every 10 minutes workflow_dispatch:  # Allow manual runs

jobs: convert: runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Install FFmpeg
    run: sudo apt update && sudo apt install -y ffmpeg

  - name: Convert M3U8 to MPD
    run: |
      ffmpeg -i "http://pars.viper01.xyz:8080/play/live.php?mac=00:1a:79:54:fc:b1&stream=563780&extension=m3u8" \
      -c copy -f dash output.mpd

  - name: Commit and Push MPD File
    run: |
      git config --global user.name "github-actions"
      git config --global user.email "actions@github.com"
      git add output.mpd
      git commit -m "Updated MPD file"
      git push
