name: Update ATV Avrupa M3U8

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Playwright
        run: |
          npm init -y
          npm install playwright
          npx playwright install --with-deps chromium

      - name: Find M3U8 and create playlist
        run: node find-m3u8.js

      - name: Commit updated playlist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add atvavrupa.m3u8

          if git diff --cached --quiet; then
            echo "M3U8 dəyişməyib."
          else
            git commit -m "Update ATV Avrupa M3U8"
            git push
          fi
